// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3r_l3tj1x9Za0XXio89OIFWIY3Um40c8',
    appId: '1:497486937927:web:66bcf53b6b41b7d84d5662',
    messagingSenderId: '497486937927',
    projectId: 'dash-6e8c2',
    authDomain: 'dash-6e8c2.firebaseapp.com',
    storageBucket: 'dash-6e8c2.appspot.com',
    measurementId: 'G-XZVH49N86G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5CA0f2J9qB4zt5YLaXCX-lMP8dKkFpmM',
    appId: '1:497486937927:android:133640261945f9744d5662',
    messagingSenderId: '497486937927',
    projectId: 'dash-6e8c2',
    storageBucket: 'dash-6e8c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mRZkuPnAFsvfYeClMRpeuB174x5-Aqk',
    appId: '1:497486937927:ios:0c6b9a9a0c06b4484d5662',
    messagingSenderId: '497486937927',
    projectId: 'dash-6e8c2',
    storageBucket: 'dash-6e8c2.appspot.com',
    iosClientId: '497486937927-80niucdhlshtgeragten316bdnpqgo8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.dash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mRZkuPnAFsvfYeClMRpeuB174x5-Aqk',
    appId: '1:497486937927:ios:0c6b9a9a0c06b4484d5662',
    messagingSenderId: '497486937927',
    projectId: 'dash-6e8c2',
    storageBucket: 'dash-6e8c2.appspot.com',
    iosClientId: '497486937927-80niucdhlshtgeragten316bdnpqgo8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.dash',
  );
}
